version: "3.7"

services:
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/api
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

volumes:
  mongodb:
